[package]
name = "pyxeledit2ldtk"
version = "0.1.0"
authors = ["spinjam <spinjam@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
zip = "0.5.11"
image = "0.23.14"